# Generated by Django 4.2.1 on 2023-05-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_status_tag_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
    ]
