# Generated by Django 4.2.1 on 2023-05-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tag_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
    ]
